export const Images = {
  homeStrokeIcon: require('../images/HomeStrokeIcon/HomeStrokeIcon.png'),
  homeFillIcon: require('../images/HomeFillIcon/HomeFillIcon.png'),
  galleryStrokeIcon: require('../images/GallaryStrokeIcon/GallaryStrokeIcon.png'),
  galleryFIllIcon: require('../images/GallaryFillIcon/GallaryFIllIcon.png'),
  addIcon: require('../images/AddIcon/AddIcon.png'),
  appSettingIcon: require('../images/SettingIcon/SettingIcon.png'),
  template1: require('../images/templateFlatList/template1.png'),
  template2: require('../images/templateFlatList/template2.png'),
  template3: require('../images/templateFlatList/template3.png'),
  template4: require('../images/templateFlatList/template4.png'),
  template5: require('../images/templateFlatList/template5.png'),
  template6: require('../images/templateFlatList/template6.png'),
  template7: require('../images/templateFlatList/template7.png'),
  template8: require('../images/templateFlatList/template8.png'),
  templateScreen1: require('../images/templateFlatList/template1.png'),
  templateScreen2: require('../images/templateFlatList/template2.png'),
  templateScreen3: require('../images/templateFlatList/template3.png'),
  templateScreen4: require('../images/templateFlatList/template4.png'),
  templateScreen5: require('../images/templateFlatList/template5.png'),
  templateScreen6: require('../images/templateFlatList/template6.png'),
  templateScreen7: require('../images/templateFlatList/template7.png'),
  templateScreen8: require('../images/templateFlatList/template8.png'),
  goBackButton: require('../images/GOBackIcon/GOBackIcon.png'),
  // bg1: require('../images/BackgroundImage/Background1.png'),
  // bg2: require('../images/BackgroundImage/Background2.png'),
  // bg3: require('../images/BackgroundImage/Background3.png'),
  // bg4: require('../images/BackgroundImage/Background4.png'),
  // bg5: require('../images/BackgroundImage/Background5.png'),
  // bg6: require('../images/BackgroundImage/Background6.png'),
  closeIcon: require('../images/CloseIcon/CloseIcon.png'),
  quoteImage1: require('../images/QuotePetter/quotePettern1.png'),
  quoteImage2: require('../images/QuotePetter/quotePettern2.png'),
  quoteImage3: require('../images/QuotePetter/quotePettern3.png'),
  quoteBackgroundImag1: require('../images/quoteBackgroundPetternImage/Quotes1.png'),
  quoteBackgroundImag2: require('../images/quoteBackgroundPetternImage/Quotes2.png'),
  quoteBackgroundImag3: require('../images/quoteBackgroundPetternImage/Quotes3.png'),
  searchIcon: require('../images/SearchIcon/searchIcon.png'),
  rightIcon: require('../images/RightIcon/Vector.png'),
  pencilEdit: require('../images/writeQuoteIcon/editQuotePencil.png'),
  cropImage: require('../images/CropeImageIcon/crop.png'),
  fontChangeIcon: require('../images/writeTextIcon/text.png'),
  colorBucketIcon: require('../images/colorBuckets/colorBucket.png'),
  verticleLineSpace: require('../images/verticleTextSpaceIcon/verticelLineSpace.png'),
  horizontleLineSpace: require('../images/horizontleSpaceIcon/horrizontalLineSpace.png'),
  textAlighIcon: require('../images/alighIcon/aligh.png'),
  alignLeft: require('../images/alighnOptions/alighnLeft.png'),
  alignCenter: require('../images/alighnOptions/alighnCenter.png'),
  alignRight: require('../images/alighnOptions/alignRight.png'),
  random: require('../images/rendomIcon/rendomIcon.png'),
  copy: require('../images/copyIcon/cpoyIcon.png'),
  download: require('../images/downloadIcon/dowenloadIcon.png'),
  share: require('../images/shareIcon/shareIcon.png'),
  leftQuoteIcon: require('../images/quoteOfTheDayQuoteIcon/leftQuoteIcon.png'),
  rightQuoteIcon: require('../images/quoteOfTheDayQuoteIcon/RightQuoteIcon.png'),
  homeScreenTemplateQuote1: require('../images/homeTemplateQuote/homeTemplateQuote1.png'),
  homeScreenTemplateQuote2: require('../images/homeTemplateQuote/homeTemplateQuote2.png'),
  homeScreenTemplate4Image: require('../images/homeTemplateQuote/templpate4Quote.png'),
  homeScreenTemplateWaterMark: require('../images/homeTemplateQuote/homeScreenTemplate5WaterMark.png'),
  homeScreenTemplate6Image: require('../images/homeTemplateQuote/template6Quote.png'),
  reelSectionObject1: require('../images/reelSrnObjects/ovel1.png'),
  reelSectionObject2: require('../images/reelSrnObjects/ovel2.png'),
  reelOvalGray1: require('../images/reelSrnObjects/grayOvel1.png'),
  reelOvalGray2: require('../images/reelSrnObjects/grayOvel2.png'),
  commenQuoteOfReal1: require('../images/commenQuoteOfReal/commenQuoteOfReal1.png'),
  commenQuoteOfReal2: require('../images/commenQuoteOfReal/commenQuoteOfReal2.png'),
  random: require('../images/random/random.png'),
  colorPiker: require('../images/colorPiker/colorPiker.png'),
  yellowBackground: require('../images/reelSrnObjects/yellowBackground.png'),
  quoteBorder: require('../images/reelSrnObjects/quoteBorder.png'),
  addAuthorPhotoIcon: require('../images/addAuthorPhotoIcon/addAuthorPhotoIcon.png'),
  settingFill: require('../images/settingFilIcon/setting.png'),
  QuoteTemplateComponent1: require('../images/homeScreenQUoteComponent/Ellipse113.png'),
  QuoteTemplateComponent2: require('../images/homeScreenQUoteComponent/Ellipse114.png'),
  QuoteTemplateComponent3: require('../images/homeScreenQUoteComponent/Ellipse116.png'),
};
